# Generated by Django 4.0.3 on 2022-03-09 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('crpto', models.ManyToManyField(through='main_app.Amount', to='main_app.cryptocurrency')),
            ],
        ),
        migrations.AddField(
            model_name='amount',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='amount',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.wallet'),
        ),
    ]
